meson: update .gitlab-ci.yml file
Signed-off-by: Pavel Hrdina <phrdina@redhat.com>
Message-Id: <1b36b8aff8e7cea42acb5177e4b7a21436a1ba38.1594891445.git.phrdina@redhat.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -7,7 +7,6 @@ stages:
   - builds
 
 .script_variables: &script_variables |
-  export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
   export CCACHE_BASEDIR="$(pwd)"
   export CCACHE_DIR="$CCACHE_BASEDIR/ccache"
   export CCACHE_MAXSIZE="500M"
@@ -50,10 +49,25 @@ stages:
   before_script:
     - *script_variables
   script:
-    - mkdir build
-    - cd build
-    - ../autogen.sh || (cat config.log && exit 1)
-    - $MAKE distcheck
+    - meson build --werror || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build dist
+
+# Default native build job only for CentOS 7 that is always run
+# meson dist fails on CentOS 7 because of old git that fails to clone
+# from shallow git repository which is done when running meson dist
+.native_build_centos_7_job_template: &native_build_centos_7_job_definition
+  stage: builds
+  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
+  cache:
+    paths:
+      - ccache/
+    key: "$CI_JOB_NAME"
+  before_script:
+    - *script_variables
+  script:
+    - meson build --werror || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build
+    - ninja -C build test
 
 # Jobs that we delegate to Cirrus CI because they require an operating
 # system other than Linux. These jobs will only run if the required
@@ -84,6 +98,8 @@ stages:
           -e "s|[@]PKGS@|$PKGS|g"
           -e "s|[@]MAKE@|$MAKE|g"
           -e "s|[@]PYTHON@|$PYTHON|g"
+          -e "s|[@]PIP@|$PIP|g"
+          -e "s|[@]PYPI_PKGS@|$PYPI_PKGS|g"
       <ci/cirrus/build.yml >ci/cirrus/$NAME.yml
     - cat ci/cirrus/$NAME.yml
     - cirrus-run ci/cirrus/$NAME.yml
@@ -102,10 +118,8 @@ stages:
   before_script:
     - *script_variables
   script:
-    - mkdir build
-    - cd build
-    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
-    - $MAKE
+    - meson build --werror $MESON_OPTS || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build
 
 
 # Native container build jobs
@@ -277,7 +291,7 @@ x64-debian-sid:
     NAME: debian-sid
 
 x64-centos-7:
-  <<: *native_build_job_definition
+  <<: *native_build_centos_7_job_definition
   variables:
     NAME: centos-7
 
@@ -420,12 +434,8 @@ website:
   before_script:
     - *script_variables
   script:
-    - mkdir build
-    - cd build
-    - ../autogen.sh --prefix=$(pwd)/../vroot || (cat config.log && exit 1)
-    - $MAKE -C docs
-    - $MAKE -C docs install
-    - cd ..
+    - meson build --prefix=$(pwd)/vroot || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build install-web
     - mv vroot/share/doc/libvirt/html/ website
   artifacts:
     expose_as: 'Website'
@@ -442,10 +452,8 @@ codestyle:
   before_script:
     - *script_variables
   script:
-    - mkdir build
-    - cd build
-    - ../autogen.sh || (cat config.log && exit 1)
-    - $MAKE syntax-check
+    - meson build || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build syntax-check
 
 
 # This artifact published by this job is downloaded to push to Weblate
@@ -459,12 +467,9 @@ potfile:
   before_script:
     - *script_variables
   script:
-    - mkdir build
-    - cd build
-    - ../autogen.sh || (cat config.log && exit 1)
-    - $MAKE -C src generated-sources
-    - $MAKE -C po libvirt.pot
-    - cd ..
+    - meson build || (cat build/meson-logs/meson-log.txt && exit 1)
+    - ninja -C build libvirt-pot-dep
+    - ninja -C build libvirt-pot
     - cp po/libvirt.pot libvirt.pot
   artifacts:
     expose_as: 'Potfile'
